// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8JIiqxkY8Fdba4AIMi1-rgtZ8_-fsuzY',
    appId: '1:612823335936:web:6118f60e5bd224e869c4e5',
    messagingSenderId: '612823335936',
    projectId: 'fcm-20041999',
    authDomain: 'fcm-20041999.firebaseapp.com',
    storageBucket: 'fcm-20041999.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjwXbNax3CYPXZbrVdV8I8sjnCnWulyEQ',
    appId: '1:612823335936:android:33b94b09838521fb69c4e5',
    messagingSenderId: '612823335936',
    projectId: 'fcm-20041999',
    storageBucket: 'fcm-20041999.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4neB6hIisBwppJFuQDCMG4iMJAKFegVY',
    appId: '1:612823335936:ios:432ca3ceb6767ada69c4e5',
    messagingSenderId: '612823335936',
    projectId: 'fcm-20041999',
    storageBucket: 'fcm-20041999.appspot.com',
    iosClientId: '612823335936-natjs2fti3galot5e5ad15spe8hsnd17.apps.googleusercontent.com',
    iosBundleId: 'com.example.fcm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4neB6hIisBwppJFuQDCMG4iMJAKFegVY',
    appId: '1:612823335936:ios:432ca3ceb6767ada69c4e5',
    messagingSenderId: '612823335936',
    projectId: 'fcm-20041999',
    storageBucket: 'fcm-20041999.appspot.com',
    iosClientId: '612823335936-natjs2fti3galot5e5ad15spe8hsnd17.apps.googleusercontent.com',
    iosBundleId: 'com.example.fcm',
  );
}
